# Generated by Django 4.2.5 on 2023-09-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(default='')),
                ('end_time', models.DateTimeField(default='')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'epmty'), (1, 'busy')], default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.stadium')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
