# Generated by Django 4.2.5 on 2023-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium', '0001_initial'),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='begin_time',
            field=models.DateTimeField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00'), (7, '14:00'), (8, '15:00'), (9, '16:00'), (10, '17:00'), (11, '18:00'), (12, '19:00'), (13, '20:00')]),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('name', 'begin_time', 'end_time')},
        ),
    ]
